language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  # The app will be deployed on PHP 5.4
  # so other versions are allowed to fail.
  allow_failures:
    - 5.6
    - 5.5
    - 5.3

install:
  - composer install --dev --no-interaction

script:
  - tests/run_tests.sh

after_script:
  - php vendor/bin/coveralls -v

deploy:
  provider: openshift
  user:
    secure: 24XmzXKzv2Acp4yAUp/kDn6EyaNeCkjw6X6C/H9s4HqaWckALhZ73QoOm1Lm7aflIrIgQWvo84aTF4MRLDKL3TFQtb6oC2bEFJM4/J9EQhDaazbQGX7e/karXMLSOugRwtYDRRGuWKaMzwxetNAKp35R3q3H7dOLtcOcI9tCWCU=
  password:
    secure: BZHiU+Bc3MVcAWr7ouA5qmjat9JW7QcPX4yLZjVoXZWAGopUFLanr4AoPjuGFn+w91F+aIzsJDjwA2zIkSjn/FEJGs+uHcnLvWE5vtEnj6UF8o7yUOhgQwHyYtc0y60oC94qDCTomDbdBYOosDVzkiZGnmL5e2N6YHC+u2Jpltc=
  app: updatemanager
  domain: spyload
  on:
    repo: pyload/updatemanager
    branch: master
    php: 5.4
  skip_cleanup: true
